services:
  api_pemrog:
    build: ./php
    image: api_pemrog_php:latest
    container_name: api_pemrog
    hostname: "api_pemrog"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on: 
      - database
  database:
    image: mariadb:10.2
    container_name: database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123!.
      MYSQL_ROOT_PASSWORD: admin123
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql  
  nginx2_pemrog:
    build: ./nginx
    image: nginx2_pemrog:latest
    container_name: nginx2_pemrog
    hostname: "nginx2_pemrog"
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_pemrog